import streamlit as st
import re
import random
import time
import base64
from datetime import datetime

# --- 1. THE POC GENERATOR ENGINE ---
def generate_poc_script(target, bug_type, cookies_b):
    """Creates a downloadable Python script to prove the vulnerability."""
    script_template = f"""
import requests

# --- POC FOR {bug_type.upper()} on {target} ---
# Generated by Smallville v16.1
target_url = "https://{target}/api/v1/user/settings" # Update to specific endpoint
attacker_cookies = {{ "session": "{cookies_b}" }}

def run_exploit():
    print(f"[*] Attempting {bug_type} on {{target_url}}...")
    # Attempting to access private data using Attacker's session
    response = requests.get(target_url, cookies=attacker_cookies, verify=True)
    
    if response.status_code == 200:
        print("[+] SUCCESS: Vulnerability Confirmed.")
        print("[+] Data Leaked:", response.text[:200])
    else:
        print(f"[-] Failed: Received status code {{response.status_code}}")

if __name__ == "__main__":
    run_exploit()
    """
    return script_template

# --- 2. UPDATED INTERFACE ---
# (Keeping your existing tabs from v16.0)
t1, t2, t3, t4 = st.tabs(["🚀 STRIKE", "🔍 SECRET MINER", "📝 BOUNTY REPORTER", "🛠️ SYSTEM"])

with t3:
    st.header("H1 Report & PoC Generator")
    
    # Input fields for the report
    bug = st.selectbox("Vulnerability Type", ["IDOR", "Broken Access Control", "AI Prompt Injection", "Secret Leak"])
    target_asset = st.session_state.get('active_target', 'example.com')
    
    col1, col2 = st.columns(2)
    with col1:
        if st.button("📄 GENERATE H1 REPORT"):
            # (Existing Report Logic from v16.0)
            st.success("Report Generated below.")
            
    with col2:
        if st.button("🐍 GENERATE POC SCRIPT"):
            # Pulling Cookie B from sidebar state for the script
            c_b = st.session_state.get('cookie_b', 'REPLACE_WITH_COOKIE_B')
            poc_code = generate_poc_script(target_asset, bug, c_b)
            
            st.code(poc_code, language="python")
            
            # Download Link for the .py file
            b64 = base64.b64encode(poc_code.encode()).decode()
            href = f'<a href="data:file/python;base64,{b64}" download="poc_exploit.py" style="color: #00ff00; text-decoration: none; border: 1px solid #00ff00; padding: 10px;">📥 Download poc_exploit.py</a>'
            st.markdown(href, unsafe_allow_html=True)

# --- 3. THE GHOST MARATHON LOGIC (Integrated) ---
with t1:
    # Adding 'Human Jitter' logic to the UI
    if st.session_state.get('is_running', False):
        st.info("Ghost Mode: Adding randomized 15-45s delays between probes to mimic human browsing.")
        st.progress(random.randint(1, 100))
